[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm run install-server",
  "npm run install-client"
]

[phases.build]
cmds = ["npm run build-client"]

[start]
cmd = "cd server && node server.js"
